FROM python:3.6
USER root
ENV PYTHONUNBUFFERED 1

ADD requirements.txt /config/
RUN pip install -r /config/requirements.txt

ADD . /src
WORKDIR /src/mysite

#RUN ./mysite/manage.py migrate
RUN ./manage.py collectstatic --no-input

CMD gunicorn mysite.wsgi -b 0.0.0.0:8080

EXPOSE 8080
