# Generated by Django 3.2 on 2021-04-20 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('hide', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('label', models.CharField(max_length=200, unique=True)),
                ('cycle_time', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('lead_time', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(auto_now=True)),
                ('friday', models.DateTimeField(auto_now=True)),
                ('card_url', models.CharField(max_length=300, unique=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='portfolio.board')),
            ],
            options={
                'ordering': ['-friday', 'name'],
            },
        ),
    ]
