# Generated by Django 3.2 on 2021-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_keyresults_keyresultvalue_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='risks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
