# Generated by Django 3.2 on 2021-04-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_keyresultvalue_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyresults',
            options={},
        ),
        migrations.RemoveField(
            model_name='keyresults',
            name='acronym',
        ),
        migrations.AlterField(
            model_name='keyresults',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='portfolio.objective'),
        ),
    ]
