# Generated by Django 3.2 on 2021-04-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210420_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresultvalue',
            name='kr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='portfolio.keyresults'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2021),
        ),
    ]
