# Generated by Django 3.2 on 2021-04-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210420_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='show_okr',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
